version: '3.8'

services:

  postgres:
    image: postgres:14.1
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - TZ=America/Sao_Paulo
    ports:
      - 5433:5432
    volumes:
      - .docker/postgresql:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 16543:80
    volumes:
      - .docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

